# Generated by Django 5.2 on 2025-04-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.IntegerField(null=True)),
                ('customer', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('collecter', models.CharField(max_length=20, null=True)),
                ('counter', models.CharField(max_length=20, null=True)),
                ('finalIndication', models.IntegerField()),
                ('initialIndication', models.IntegerField()),
                ('intermediateIndication', models.IntegerField(blank=True, null=True)),
                ('cubicMeters', models.IntegerField(blank=True, null=True)),
                ('billableCubicMeters', models.IntegerField(blank=True, null=True)),
                ('hydronomistsCubicMeters', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('hydronomistsRight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('paymentDate', models.DateField(null=True)),
                ('receivedBy', models.CharField(max_length=10, null=True)),
                ('receiptNumber', models.IntegerField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('viberMsg', models.CharField(max_length=200, null=True)),
                ('notes', models.TextField(null=True)),
                ('fields', models.CharField(max_length=20, null=True)),
                ('olivesNumber', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
