# Generated by Django 5.2 on 2025-05-11 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WaterConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.IntegerField(null=True)),
                ('customer', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('collecter', models.CharField(max_length=20, null=True)),
                ('counter', models.CharField(max_length=20, null=True)),
                ('finalIndication', models.IntegerField()),
                ('initialIndication', models.IntegerField()),
                ('intermediateIndication', models.IntegerField(blank=True, null=True)),
                ('cubicMeters', models.IntegerField(blank=True, null=True)),
                ('billableCubicMeters', models.IntegerField(blank=True, null=True)),
                ('hydronomistsCubicMeters', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('hydronomistsRight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('paymentDate', models.DateField(null=True)),
                ('receivedBy', models.CharField(max_length=10, null=True)),
                ('receiptNumber', models.IntegerField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('viberMsg', models.CharField(max_length=200, null=True)),
                ('notes', models.TextField(null=True)),
                ('fields', models.CharField(max_length=20, null=True)),
                ('olivesNumber', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('fathersName', models.CharField(blank=True, max_length=100, null=True)),
                ('afm', models.CharField(blank=True, max_length=9, null=True, unique=True)),
                ('mobilePhone', models.CharField(blank=True, max_length=10, null=True)),
                ('member', models.BooleanField(default=True)),
                ('payAsMember', models.BooleanField(default=True)),
                ('isActive', models.BooleanField(default=False)),
                ('aa', models.IntegerField(blank=True, null=True, unique=True)),
                ('placeΟfΡesidence', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['surname', 'name', 'fathersName'],
                'unique_together': {('surname', 'name', 'fathersName')},
            },
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(blank=True, max_length=20, null=True)),
                ('olivesNumber', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synet.persons')),
            ],
        ),
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collecter', models.CharField(max_length=20)),
                ('counter', models.CharField(blank=True, max_length=20, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='synet.persons')),
            ],
            options={
                'ordering': ['collecter'],
            },
        ),
        migrations.CreateModel(
            name='WaterCons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('finalIndication', models.IntegerField()),
                ('initialIndication', models.IntegerField()),
                ('intermediateIndication', models.IntegerField(blank=True, null=True)),
                ('cubicMeters', models.IntegerField(blank=True, null=True)),
                ('billableCubicMeters', models.IntegerField(blank=True, null=True)),
                ('hydronomistsCubicMeters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costPerMeter', models.DecimalField(blank=True, decimal_places=2, default=0.3, max_digits=10, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hydronomistsRight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('viberMsg', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synet.counters')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synet.persons')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='synet.fields')),
            ],
        ),
        migrations.CreateModel(
            name='Paids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paymentDate', models.DateField(blank=True, null=True)),
                ('receiptNumber', models.IntegerField(blank=True, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='synet.receivers')),
                ('irrigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='synet.watercons')),
            ],
        ),
    ]
