# Generated by Django 5.2 on 2025-04-30 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collecter', models.CharField(max_length=20, null=True)),
                ('counter', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=20, null=True)),
                ('olivesNumber', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synet.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Paids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('paymentDate', models.DateField(null=True)),
                ('receivedBy', models.CharField(max_length=10, null=True)),
                ('receiptNumber', models.IntegerField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synet.customers')),
            ],
        ),
        migrations.CreateModel(
            name='WaterCons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.IntegerField(null=True)),
                ('date', models.DateField()),
                ('finalIndication', models.IntegerField()),
                ('initialIndication', models.IntegerField()),
                ('intermediateIndication', models.IntegerField(blank=True, null=True)),
                ('cubicMeters', models.IntegerField(blank=True, null=True)),
                ('billableCubicMeters', models.IntegerField(blank=True, null=True)),
                ('hydronomistsCubicMeters', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('hydronomistsRight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('viberMsg', models.CharField(max_length=200, null=True)),
                ('notes', models.TextField(null=True)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synet.counters')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synet.customers')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synet.fields')),
            ],
        ),
    ]
