# Generated by Django 5.2 on 2025-05-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persons',
            old_name='placeΟfΡesidence',
            new_name='placeOfResidence',
        ),
    ]
