# Generated by Django 5.2 on 2025-05-12 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synet', '0002_rename_placeοfρesidence_persons_placeofresidence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persons',
            old_name='mobilePhone',
            new_name='phone',
        ),
    ]
