# Generated by Django 5.2 on 2025-05-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synet', '0002_counters_customers_fields_paids_watercons'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='fathersName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='surname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
