# Generated by Django 5.2 on 2025-05-13 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synet', '0003_rename_mobilephone_persons_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='watercons',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watercons_receipts', to='synet.paids'),
        ),
        migrations.AlterField(
            model_name='counters',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='synet.persons'),
        ),
        migrations.AlterField(
            model_name='fields',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='synet.persons'),
        ),
        migrations.AlterField(
            model_name='paids',
            name='irrigation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_irrigations', to='synet.watercons'),
        ),
        migrations.AlterField(
            model_name='paids',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='synet.receivers'),
        ),
        migrations.AlterField(
            model_name='watercons',
            name='counter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='synet.counters'),
        ),
        migrations.AlterField(
            model_name='watercons',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='synet.persons'),
        ),
        migrations.AlterField(
            model_name='watercons',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='synet.fields'),
        ),
    ]
