# Generated by Django 5.2 on 2025-05-01 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synet', '0003_customers_fathersname_customers_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='customer',
        ),
    ]
