# Generated by Django 5.2 on 2025-05-13 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synet', '0004_watercons_receipt_alter_counters_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paids',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='synet.persons'),
        ),
    ]
