# Generated by Django 5.2 on 2025-05-01 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synet', '0004_remove_customers_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='counters',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='synet.customers'),
        ),
    ]
