# Generated by Django 5.2 on 2025-05-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synet', '0005_paids_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paids',
            name='receiptNumber',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
