# Generated by Django 5.2 on 2025-05-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synet', '0005_counters_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counters',
            options={'ordering': ['collecter']},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'ordering': ['surname', 'name']},
        ),
        migrations.AlterField(
            model_name='customers',
            name='surname',
            field=models.CharField(max_length=100),
        ),
    ]
