# Generated by Django 5.2 on 2025-05-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synet', '0006_alter_counters_options_alter_customers_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='afm',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='member',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='payAsMember',
            field=models.BooleanField(default=True),
        ),
    ]
