# Generated by Django 5.2 on 2025-05-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synet', '0006_alter_paids_receiptnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='paids',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
