# Generated by Django 5.2 on 2025-06-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synet', '0007_paids_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='counters',
            name='lastIndication',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
