# Generated by Django 5.2 on 2025-05-03 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synet', '0007_customers_afm_customers_member_customers_payasmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='paids',
            name='receivedBy',
        ),
        migrations.AddField(
            model_name='paids',
            name='irrigation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='synet.watercons'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='afm',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='fathersName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paids',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='synet.receivers'),
        ),
    ]
