# Generated by Django 5.2 on 2025-06-29 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synet', '0008_counters_lastindication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaterConsumption',
        ),
    ]
