# Generated by Django 5.2 on 2025-05-03 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synet', '0008_receivers_remove_paids_receivedby_paids_irrigation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paids',
            name='customer',
        ),
    ]
