# Generated by Django 5.2 on 2025-05-04 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synet', '0009_remove_paids_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counters',
            name='collecter',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='counters',
            name='counter',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='counters',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='synet.customers'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='afm',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='customers',
            name='fathersName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customers',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fields',
            name='field',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='paids',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paids',
            name='irrigation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='synet.watercons'),
        ),
        migrations.AlterField(
            model_name='paids',
            name='paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paids',
            name='paymentDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paids',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='synet.receivers'),
        ),
        migrations.AlterField(
            model_name='receivers',
            name='receiver',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='watercons',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='watercons',
            name='field',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='synet.fields'),
        ),
        migrations.AlterField(
            model_name='watercons',
            name='hydronomistsCubicMeters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='watercons',
            name='hydronomistsRight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='watercons',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='watercons',
            name='serialNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watercons',
            name='viberMsg',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
