# Generated by Django 5.2 on 2025-05-04 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synet', '0010_alter_counters_collecter_alter_counters_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counters',
            name='counter',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='counters',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='synet.customers'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='afm',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='fathersName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fields',
            name='field',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='watercons',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='synet.fields'),
        ),
        migrations.AlterField(
            model_name='watercons',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watercons',
            name='viberMsg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
