# Generated by Django 5.2 on 2025-05-04 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synet', '0012_alter_counters_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counters',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='synet.customers'),
        ),
    ]
