# Generated by Django 5.2 on 2025-05-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synet', '0013_alter_counters_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='watercons',
            name='costPerMeter',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.3, max_digits=10, null=True),
        ),
    ]
