# Generated by Django 5.2 on 2025-05-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synet', '0014_watercons_costpermeter'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
