# Generated by Django 5.2 on 2025-05-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synet', '0015_customers_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
