# Generated by Django 5.2 on 2025-05-11 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synet', '0016_alter_customers_isactive'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Persons',
        ),
    ]
