# Generated by Django 5.2 on 2025-05-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synet', '0017_rename_customers_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='aa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
