# Generated by Django 5.2 on 2025-05-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synet', '0018_persons_aa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persons',
            options={'ordering': ['surname', 'name', 'fathersName']},
        ),
        migrations.AlterField(
            model_name='persons',
            name='aa',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='afm',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='persons',
            unique_together={('surname', 'name', 'fathersName')},
        ),
    ]
