# Generated by Django 5.2 on 2025-05-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synet', '0019_alter_persons_options_alter_persons_aa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='placeΟfΡesidence',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
