# Generated by Django 5.2 on 2025-05-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synet', '0020_persons_placeοfρesidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='mobilePhone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
