# Generated by Django 5.2 on 2025-05-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synet', '0021_persons_mobilephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
